server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: false
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
        - id: workspace-service
          uri: lb://workspace-service
          predicates:
            - Path=/api/v1/workspaces/**
        - id: board-service
          uri: lb://board-service
          predicates:
            - Path=/api/v1/boards/**
        - id: list-service
          uri: lb://list-service
          predicates:
            - Path=/api/v1/lists/**
        - id: card-service
          uri: lb://card-service
          predicates:
            - Path=/api/v1/cards/**
        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/api/v1/comments/**
        - id: label-service
          uri: lb://label-service
          predicates:
            - Path=/api/v1/labels/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notifications/**
        - id: audit-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/audit/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
